apiVersion: v1
kind: Template
labels:
  template: f8a-worker-scaler
metadata:
  name: f8a-worker-scaler
  annotations:
    description: f8a-worker-scaler
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-worker-scaler
    name: f8a-worker-scaler
  spec:
    replicas: 1
    selector:
      service: f8a-worker-scaler
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: f8a-worker-scaler
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: DC_NAME
            value: "${DC_NAME}"
          - name: SQS_QUEUE_NAME
            value: "${SQS_QUEUE_NAME}"
          - name: DEFAULT_REPLICAS
            value: "${DEFAULT_REPLICAS}"
          - name: MAX_REPLICAS
            value: "${MAX_REPLICAS}"
          - name: SCALE_COEF
            value: "${SCALE_COEF}"
          - name: SLEEP_INTERVAL
            value: "${SLEEP_INTERVAL}"
          - name: DRY_RUN
            value: "${DRY_RUN}"
          - name: OC_PROJECT
            value: "${OC_PROJECT}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-worker-scaler
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            exec:
              command: ["true"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["/home/scaler/liveness_check.sh"]
            initialDelaySeconds: 5
            periodSeconds: 120
            timeoutSeconds: 5
        restartPolicy: Always
        serviceAccountName: workerscaler
    triggers:
    - type: ConfigChange

parameters:
- description: Name of the deployment config to scale
  displayName: Deployment config name
  required: true
  name: DC_NAME
  value: "bayesian-worker-ingestion"

- description: Default (minimum) number of replicas
  displayName: Min replicas
  required: true
  name: DEFAULT_REPLICAS
  value: "1"

- description: Max number of replicas
  displayName: Max replicas
  required: true
  name: MAX_REPLICAS
  value: "2"

- description: Number of messages that singe worker can process in some reasonable time
  displayName: Scale coefficient
  required: true
  name: SCALE_COEF
  value: "100"

- description: How long to sleep between runs (in minutes).
  displayName: Sleep interval
  required: true
  name: SLEEP_INTERVAL
  value: "5"

- description: Dry run - do not scale anything (true/false)
  displayName: Dry run
  required: true
  name: DRY_RUN
  value: "false"

- description: A comma-separated list of queues to monitor (without deployment prefix)
  displayName: Queues to monitor
  required: true
  name: SQS_QUEUE_NAME
  value: "ingestion_bayesianFlow_v0,ingestion_bayesianPackageFlow_v0"

- description: Name of the openshift project used for oc command
  displayName: Openshift Project Name
  required: true
  name: OC_PROJECT
  value: "bayesian-preview"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/rhel-fabric8-analytics-worker-scaler"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
